name: End to end tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

#defaults:
#  run:
#    working-directory: ./backend

jobs:
  build_backend:
    defaults:
      run:
        working-directory: ./backend

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build

  build_frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run check-types
    - run: npm run lint

  build_success:
    defaults:
      run:
        working-directory: ./test

    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend]
    steps:
    - run: pip install -r requirements_dev.txt
    - run: python run_tests.py
