name: End to end tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  DISPLAY: :0

jobs:
  build:
    defaults:
      run:
        working-directory: .

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Build backend
      run: |
        cd ./backend
        cargo build
    - name: Build frontend
      run: |
        cd ./frontend
        npm ci
        npm run dist
        ls out
    - name: Setup xvfb (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
        # start xvfb in the background
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - name: Setup chromedriver
      uses: nanasess/setup-chromedriver@master
      with:
        chromedriver-version: '87.0.4280.88'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Get python dependencies
      run: pip install -r requirements_dev.txt
    - name: Run tests
      run: |
        which chromedriver
        cd ./test/tests
        pytest
