name: End to end tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

#defaults:
#  run:
#    working-directory: ./backend

jobs:
  build:
    defaults:
      run:
        working-directory: .

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Build backend
      run: |
        cd ./backend
        cargo build
    - name: Build frontend
      run: |
        cd ./frontend
        npm ci
        npm run dist
        ls out
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Get python dependencies
      run: pip install -r requirements_dev.txt
    - name:
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./test/tests
        run: pytest
